vich_uploader:
    db_driver: orm

    mappings:
        img_footer
            uri_prefix: '%img_footer%'
            upload_destination: '%kernel.project_dir%/public%img_footer%'
            namer: vitch\uploaderBundle\Naming\SmartUniquNamer
            delete_on_upload: false
            delete_on_reemove: false
